services:
  db:
    image: postgres:17.0
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  django:
    container_name: django
    build: .
    volumes:
      - ./transcendence:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HOSTNAME=${HOSTNAME}
    command: ./entrypoint.sh daphne -e ssl:8000:privateKey=/app/key.pem:certKey=/app/cert.pem transcendence.asgi:application
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
